### ISSUE TITLE
Remove example that relies on runtime crate

### ISSUE THREAD

**Issue by secretfader** [rustasync/tide#333]
Tide's repository currently [hosts an example](https://github.com/rustasync/tide/blob/master/examples/runtime.rs) that utilizes the [`runtime`](https://github.com/rustasync/runtime) crate. While `runtime` presents a easy-to-understand async programming environment, I don't think it should be a required dependency of Tide (either in development or production).

I believe Tide's dependency on `runtime` is slowing completion of PRs like #307, which updates `tokio` to version `0.2`. Having stale PRs on a project that is owned by a working group isn't the best look; I understand why [users and contributors are beginning to pose questions concerning Tide's future](https://github.com/rustasync/tide/issues/325).

I plan on opening a PR to support this issue, which can be merged by any maintainers who agree with this proposal. cc: @rustasync/maintainers

**Comment by Nemo157** [comment]
👍 [runtime has been publicly announced as deprecated](https://discordapp.com/channels/442252698964721669/474974025454452766/633493318164021248), even if it hasn't actually been deprecated yet.

I would like to still have an example of using the `http-service` abstraction directly instead of the default runtime, but to avoid extra dependencies that could be done through `http-service-hyper::run` (and leave examples of customising the runtime below that up to `http-service-hyper`'s documentation).

**Comment by secretfader** [comment]
It sounds like my proposal is surprisingly well-timed! I can throw together an example with `http-service-hyper` and include it in #334 or PR it separately. Do you have a preference, @Nemo157?

**Comment by rw** [comment]
Maybe OT, but what's the alternative to `runtime`? I really like it.

**Comment by Nemo157** [comment]
@rw I don't know of any other attempts at providing a whole abstraction over async runtimes like runtime did. There are bits and pieces around the place, like `{futures,tokio}::io::{AsyncRead,AsyncWrite}` for the base IO, `{futures::task::Spawn,tokio::executor::{Executor,TypedExecutor}}` for task spawning, `hyper::server::accept::Accept` for something similar to `TcpListener`.

I hope that after a few months, once the ecosystem has stabilized a bit, there can be another attempt at something like `runtime` providing a fully capable abstraction.
